[package]
name = "rusticnes-sdl"
version = "0.1.1"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]
build = "build.rs"

[dependencies]
dirs = "5.0.1"
image = "0.24.6"
sdl2 = "0.35.2"
nfd2 = "0.3.1"
rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core", rev = "b81ec27e481886278d29052203050304011f53cc" }
rusticnes-ui-common = { git = "https://github.com/zeta0134/rusticnes-ui-common", rev = "26dd47b1f634da9e36d926bcc69fe55a9d3b8cc3" }
