[package]
name = "rusticnes-sdl"
version = "0.1.0"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.19"
sdl2 = "0.30.0"
nfd2 = "0.2.3"
rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core" }
rusticnes-ui-common = { git = "https://github.com/zeta0134/rusticnes-ui-common" }
