[package]
name = "rusticnes-sdl"
version = "0.1.1"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.19"
sdl2 = "0.34.5"
nfd2 = "0.2.3"
rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core", rev = "3fba9d95d7842d5805c9acea2aaa615f07b10fb8" }
rusticnes-ui-common = { git = "https://github.com/zeta0134/rusticnes-ui-common", rev = "e9ad9a0edcf742e8dfb3ad5490808f069a10282b" }
