[package]
name = "rusticnes-wasm"
version = "0.1.0"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.0"
wasm-bindgen = "0.2.69"
rusticnes-core = { git = "https://github.com/zeta0134/rusticnes-core" }
rusticnes-ui-common = { git = "https://github.com/zeta0134/rusticnes-ui-common" }

