[package]
name = "rustico-cli"
version = "0.1.0"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]

[dependencies]
image = "0.19"
rustico-core = { path = "../core" }
rustico-ui-common = { path = "../ui-common" }