[piano_roll]
canvas_width = 480
canvas_height = 270
key_length = 16
key_thickness = 4
octave_count = 9
scale_factor = 1
speed_multiplier = 1
starting_octave = 0
waveform_height = 32
oscilloscope_glow_thickness = 2.5
oscilloscope_line_thickness = 0.5