[package]
name = "rustico-sdl"
version = "0.1.1"
authors = ["Nicholas Flynt <thegamefreak0134@gmail.com>"]
build = "build.rs"

[dependencies]
dirs = "5.0.1"
image = "0.24.6"
sdl2 = "0.36.0"
nfd2 = "0.3.1"
rustico-core = { path = "../core" }
rustico-ui-common = { path = "../ui-common" }
