[piano_roll.colors.2A03.DMC]
static = "rgb(96, 32, 192)"

[piano_roll.colors.2A03.Noise]
mode0 = "rgb(192, 192, 192)"
mode1 = "rgb(128, 240, 255)"

[piano_roll.colors.2A03."Pulse 1"]
duty0 = "hsv(340, 25%, 100%)"
duty1 = "hsv(350, 55%, 100%)"
duty2 = "hsv(360, 75%, 100%)"
duty3 = "hsv(350, 55%, 100%)"

[piano_roll.colors.2A03."Pulse 2"]
duty0 = "hsv(40, 25%, 100%)"
duty1 = "hsv(50, 55%, 100%)"
duty2 = "hsv(60, 75%, 100%)"
duty3 = "hsv(50, 55%, 100%)"

[piano_roll.colors.2A03.Triangle]
static = "#40FF40"
[piano_roll.colors.MMC5.PCM]
static = "rgb(224, 24, 64)"

[piano_roll.colors.MMC5."Pulse 1"]
static = "rgb(224, 24, 64)"

[piano_roll.colors.MMC5."Pulse 2"]
static = "rgb(180, 12, 40)"
[piano_roll.colors.N163."NAMCO 1"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 2"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 3"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 4"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 5"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 6"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 7"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"

[piano_roll.colors.N163."NAMCO 8"]
gradient_high = "hsv(35, 22%, 80%)"
gradient_low = "hsv(5, 80%, 60%)"
[piano_roll.colors.VRC6."Pulse 1"]
duty0 = "hsv(330, 22%, 94%)"
duty1 = "hsv(330, 32%, 86%)"
duty2 = "hsv(330, 42%, 78%)"
duty3 = "hsv(330, 52%, 70%)"
duty4 = "hsv(330, 63%, 62%)"
duty5 = "hsv(330, 73%, 54%)"
duty6 = "hsv(330, 83%, 46%)"
duty7 = "hsv(330, 93%, 48%)"

[piano_roll.colors.VRC6."Pulse 2"]
duty0 = "hsv(300, 22%, 94%)"
duty1 = "hsv(300, 32%, 86%)"
duty2 = "hsv(300, 42%, 78%)"
duty3 = "hsv(300, 52%, 70%)"
duty4 = "hsv(300, 63%, 62%)"
duty5 = "hsv(300, 73%, 54%)"
duty6 = "hsv(300, 83%, 46%)"
duty7 = "hsv(300, 93%, 48%)"

[piano_roll.colors.VRC6.Sawtooth]
mode0 = "#077d5a"
mode1 = "#9fb8ed"
[piano_roll.colors.YM2149F.A]
static = "rgb(32, 144, 204)"

[piano_roll.colors.YM2149F.B]
static = "rgb(24, 104, 228)"

[piano_roll.colors.YM2149F.C]
static = "rgb(16, 64, 248)"